/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.pgreze.kollections

import org.spekframework.spek2.Spek
import org.spekframework.spek2.style.specification.describe

class CounterTest : Spek({

    describe("a counter") {
        val counter = counterOf<String>()

        it("should count") {

        }
    }
})
